### PR TITLE
Adds colcon ignore in order to ignore ROS1 packages from colcon build in ROS2

### PR DESCRIPTION
**Pull request by jrgnicho**

### CODE REVIEW

**Comment by jrgnicho** [comment]
@Levi-Armstrong  it errors out whenever it finds any catkin related commands in the CMakeLists.txt.  This change would allow to build the pure cmake packages in a colcon ROS2 workspace.

**Comment by Levi-Armstrong** [comment]
I believe the reason it errors out using colcon is because the package.xml has not been updated to format 2 and it needs the [<build_type>catkin</build_type>](https://www.ros.org/reps/rep-0149.html#build-type-multiple) added.

**Comment by jrgnicho** [comment]
It would still fail in a ROS2 workspace because the ROS1 libraries aren't part of that environment

**Comment by jrgnicho** [comment]
Furthermore, in a colcon ROS2 ws that also uses tesseract_ros2 there will be conflicting packages because they're named the same as those in tesseract/tesseract_ros

**Comment by Levi-Armstrong** [comment]
Lets discuss further on issue #207.

**Comment by mpowelson** [comment]
@Levi-Armstrong Until @207 is implemented, can we just COLCON_IGNORE tesseract_ros and tesseract_python? Having these in here is making CI problematic.

**Comment by mpowelson** [comment]
@Levi-Armstrong ping

**Comment by Levi-Armstrong** [comment]
@jrgnicho Can you rebase? I think it should fix CI to get this merged.

**Comment by mpowelson** [comment]
I think we'll have to ignore tesseract_python as well since it uses tesseract_rosutils

**Comment by jrgnicho** [comment]
@Levi-Armstrong I just rebased

**Comment by Levi-Armstrong** [comment]
@jrgnicho Something is still not happy.

**Comment by mpowelson** [comment]
I don't think this is going to work. I thought that catkin only obeyed CATKIN_IGNORE, but colcon ignored all. That does not appear to be the case. See [HERE](https://github.com/ros-infrastructure/catkin_pkg/blob/35137d5522fc4b4140bf24d4d35373a1ff74e4e9/src/catkin_pkg/packages.py#L47) linked from [THIS issue](https://answers.ros.org/question/306624/ignore-package-in-colcon-but-not-catkin/) which I see Jorge is a part of. Perhaps we should just add a check to the package.xml/cmake like we do in yak_ros? 

It looks like it doesn't like that we are trying to run tests on tesseract_ros_examples using PKGS_DOWNSTREAM.

**Comment by mpowelson** [comment]
This has been replaced by #241

**Pull request closed without merging**
