### PR TITLE
Merge feature/CommandLanguage branch into master

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by mpowelson** [comment]
If we are going to address #511 we probably should before we merge this. Updating user code is already going to be painful.

**Comment by Levi-Armstrong** [comment]
@mpowelson You good with merging this into master? A tag has been created for the current state of master.

**Comment by mpowelson** [comment]
> @mpowelson You good with merging this into master? A tag has been created for the current state of master.

In concept yes. I'm curious why you had to rebase it. Shouldn't we merge it in from the feature branch on this repo? I would think we would merge master into feature/CommandLanguage, add any fixes we need to, merge feature/CommandLanguage into master.

**Comment by mpowelson** [comment]
That said, this is already done and passing CI. So on second thought, go for it.

**Pull request merged**
