### PR TITLE
Move tesseract_command_langauge package to tesseract_planning repo

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@mpowelson and @marip8 You good with merging this?

**Comment by mpowelson** [comment]
Fine with me

**Comment by marip8** [comment]
My suggestion [here](https://github.com/ros-industrial-consortium/tesseract_planning/discussions/7) was to only migrate the planning-specific command language features into the planning repository. Would it be beneficial to leave some of the core types (`Instruction`, `CompositeInstruction`, etc.) in the main repository for other `tesseract` to build on? Or is the ultimate plan for the core command language code to be in its own repository?

**Comment by Levi-Armstrong** [comment]
> My suggestion [here](https://github.com/ros-industrial-consortium/tesseract_planning/discussions/7) was to migrate only the planning-specific command language features into the planning repository. Would it be beneficial to leave some of the core types (`Instruction`, `CompositeInstruction`, etc.) in the main repository for other `tesseract` to build on? Or is the ultimate plan for the core command language code to be in its own repository? Or is its only use case for planning?

I think it would be good to move it to the tesseact_planning until things are more stable. I believe somethings will be changing with the core items. Then once things are more stable we can break things out into its own repository or move into tesseract core repository. What do you think?

**Pull request merged**
