### PR TITLE
Update URDF parser documentation

### PR DESCRIPTION
**Pull request by marip8**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@marip8 what issue did you have. The parser looks for `point_cloud` shown [here](https://github.com/ros-industrial-consortium/tesseract/blob/9690d921417791a76e746d517fff30a75c59ffad/tesseract/tesseract_urdf/include/tesseract_urdf/octomap.h#L113)

**Comment by marip8** [comment]
I see. The error printout on the terminal is wrong then ([see here](https://github.com/ros-industrial-consortium/tesseract/blob/9690d921417791a76e746d517fff30a75c59ffad/tesseract/tesseract_urdf/include/tesseract_urdf/octomap.h#L63)). I'll revise this PR

**Comment by Levi-Armstrong** [comment]
I see.

**Comment by marip8** [comment]
@Levi-Armstrong @drchrislewis this should resolve the issue I ran into

**Pull request merged**
