### PR TITLE
Trajopt planner unit tests

### PR DESCRIPTION
**Pull request by mpowelson**

### CODE REVIEW

**Comment by mpowelson** [comment]
@Levi-Armstrong I don't really know what else I could add to these. We don't return the problem to check that the costs were actually added (perhaps we should). I'm just checking that the results have the correct number of rows and that it doesn't crash.

What would you think about adding a generateProblem method to these TrajOpt planners? They would take a config and return the problem. solve() would then start by calling that function. I don't know that it would really have much use other than testing.

**Comment by Levi-Armstrong** [comment]
One option is to move the code that creates the problem into a protected method of the TrajOptArrayPlanner Class. Then in your test create a TrajOptArrayPlannerTest which inherits from TrajOptArrayPlanner and add a method to TrajOptArrayPlannerTest  which would return the problem  or runs the actual tests, because it has access to the protected methods. This would prevent you form having to add new things to the main class.

**Comment by mpowelson** [comment]
> One option is to move the code that creates the problem into a protected method of the TrajOptArrayPlanner Class. Then in your test create a TrajOptArrayPlannerTest which inherits from TrajOptArrayPlanner and add a method to TrajOptArrayPlannerTest which would return the problem or runs the actual tests, because it has access to the protected methods. This would prevent you form having to add new things to the main class.

You have done this before. I like it.

**Comment by Levi-Armstrong** [comment]
It looks like new test is failing and the clang formatting failed.

**Comment by Levi-Armstrong** [comment]
@mpowelson Lets also switch this to the be against the master branch.

**Comment by mpowelson** [comment]
@Levi-Armstrong See #100

**Pull request closed without merging**
