### PR TITLE
Use thread for contact computation in contact_monitor node

### PR DESCRIPTION
**Pull request by johnwason**
Use a background thread for computing contact report. This avoids stale joint_states messages and gives a small performance boost.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@johnwason Everything looks good. Could you run clang format on the file to fix the formatting?

**Comment by johnwason** [comment]
How do I run clang format?

**Comment by jrgnicho** [comment]
@Levi-Armstrong are you still wanting any further reviews on this?

**Comment by Levi-Armstrong** [comment]
This is now in PR #162

**Pull request closed without merging**
