### PR TITLE
Planner Verbosity

### PR DESCRIPTION
**Pull request by marip8**
This PR adds functionality for printing collision information about a trajectory to the console. It also adds an additional optional boolean argument to the `solve` method of the motion planner base class about whether or not to print important motion planning information

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
The PR looks good except it looks like the wrong version of clang was ran. Below is the command line command to run for tesseract.

```
find . -type d \( -name bullet3_ros -o -name fcl_ros -o -name libccd_ros -o -name gtest_ros -o -name tesseract_ext \) -prune -o -type f -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\|hxx\)' -exec clang-format-8 -style=file -i {} \;
```

**Comment by Levi-Armstrong** [comment]
@marip8 If you delete the clang format commit, I will create a PR against yours using clang-8.

**Comment by marip8** [comment]
@Levi-Armstrong I just removed the clang formatting commit as requested

**Comment by Levi-Armstrong** [comment]
@marip8 I just pushed clang format. If CI passes I will merge.

**Pull request merged**
