### PR TITLE
Add test to benchmark ACM isCollisionAllowed

### PR DESCRIPTION
**Pull request by mpowelson**
This is the benchmarking test I made to compare the new ACM method to the old one.

### CODE REVIEW

**Comment by arocchi** [comment]
Would be very nice to report also numeric results of timing with the two implementations (`pair` vs string concatenation)!

**Comment by mpowelson** [comment]
My testing was pretty informal, but on my PC it was taking ~2.7e-7s for both

**Comment by mpowelson** [comment]
@Levi-Armstrong I added a regular assert that the average was less than 1e-4s. That way it won't run on debug builds.

**Comment by Levi-Armstrong** [comment]
@mpowelson I believe assert only get included when building in debug and are not included in release.

**Comment by mpowelson** [comment]
That was the idea. I was concerned that debug releases might be slower and artificially fail the test.

**Comment by mpowelson** [comment]
Should be fixed.

**Pull request merged**
