### PR TITLE
Exposes joint weighting

### PR DESCRIPTION
**Pull request by DavidMerzJr**
@Levi-Armstrong 

The changes made earlier today.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@johnwason Is it preferred to use std::vector<double> or Eigen::VectorXd for SWIG C++ to python?

**Comment by johnwason** [comment]
Either way can work, but Eigen::VectorXd is probably more of a canonical representation.

**Comment by Levi-Armstrong** [comment]
@johnwason Thank you. I update it to use Eigen.

**Comment by Levi-Armstrong** [comment]
See #165

**Pull request closed without merging**
