### PR TITLE
Deploy API documentation gh-pages branch

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
This adds a workflow to deploy doxygen documentation to the gh-pages branch when content is pushed to the master branch.

### CODE REVIEW

**Comment by mpowelson** [comment]
Looks reasonable. Do you have this generating on your fork? Should we add a link in the readme?

**Comment by Levi-Armstrong** [comment]
It is available on on my gh-pages branch but not sure how to visualize it from here. How did you visualize yours? Once it is in upstream the github.io page should work. I will update the readme with links.

**Comment by mpowelson** [comment]
I went into the settings on my fork and generated gh pages from that branch on my fork.

**Comment by Levi-Armstrong** [comment]
@mpowelson You good with merging? I assume I may have to fix something with the benchmarks but we will see how this works.

**Comment by mpowelson** [comment]
Sure. Go for it.

**Pull request merged**
