### PR TITLE
Add ability to change joint limits 

### PR DESCRIPTION
**Pull request by mpowelson**

### CODE REVIEW

**Comment by mpowelson** [comment]
@Levi-Armstrong Could you take a look at this? Is this all I have to do or will I need to trigger the manipulator manager to update somehow?

**Comment by Levi-Armstrong** [comment]
For the environment that is it, but we need to figure out how to update the manipulator manager. I starting to thing we should have the environment own the manipulator manager then it could handle updating things like this. What do you think?

**Comment by mpowelson** [comment]
The ManipulatorManager has an Environment::ConstPtr as a class member. I'm really not sure. It doesn't not make sense. The environment already owns the collision checkers. I will say though, if we do that, there isn't really that much in the Tesseract anymore.

I wonder if we should instead move the CommandHistory aspect to the Tesseract. We could make the commands TesseractCommands then we could register a command history callback where each "manager" (environment, manipulator, maybe collision) registers a function to be called when the CommandHistory is updated.

**Comment by mpowelson** [comment]
Also, I'm not entirely sure that this doesn't do it as is. The joint limits are a pointer in the scene graph. I assume the scene graph in the manipulator manager is the same one as in the environment. Do you think there is a copy somewhere I would need to update?

**Comment by Levi-Armstrong** [comment]
> Also, I'm not entirely sure that this doesn't do it as is. The joint limits are a pointer in the scene graph. I assume the scene graph in the manipulator manager is the same one as in the environment. Do you think there is a copy somewhere I would need to update?

Not sure,  the kinematics objects make a copy so they would need to be updated.

**Comment by Levi-Armstrong** [comment]
> The ManipulatorManager has an Environment::ConstPtr as a class member. I'm really not sure. It doesn't not make sense. The environment already owns the collision checkers. I will say though, if we do that, there isn't really that much in the Tesseract anymore.
> 
> I wonder if we should instead move the CommandHistory aspect to the Tesseract. We could make the commands TesseractCommands then we could register a command history callback where each "manager" (environment, manipulator, maybe collision) registers a function to be called when the CommandHistory is updated.

I think either way would work, though not sure which would be the better approach.

**Comment by mpowelson** [comment]
I see now. They get parsed in to KDL structures.

For now, I could just add an update method to the FK and IK structures and the manipulator manager (which just calls update on all of the solvers). Internally, they could just call init again.

**Comment by Levi-Armstrong** [comment]
> I see now. They get parsed in to KDL structures.
> 
> For now, I could just add an update method to the FK and IK structures and the manipulator manager (which just calls update on all of the solvers). Internally, they could just call init again.

sounds good to me.

**Comment by mpowelson** [comment]
> > I see now. They get parsed in to KDL structures.
> > For now, I could just add an update method to the FK and IK structures and the manipulator manager (which just calls update on all of the solvers). Internally, they could just call init again.
> 
> sounds good to me.

@Levi-Armstrong I'll have to change fwd_kin_manipulators_default_ to store Ptrs instead of ConstPtr. Unless there is another way I should be doing this.

**Comment by mpowelson** [comment]
Do fwd_kin_manipulators and fwd_kin_manipulators_default contain duplicates? If I just loop over fwd_kin_manipulators does that include fwd_kin_manipulators_default?

**Comment by Levi-Armstrong** [comment]
> Do fwd_kin_manipulators and fwd_kin_manipulators_default contain duplicates? If I just loop over fwd_kin_manipulators does that include fwd_kin_manipulators_default?

It should.

**Comment by mpowelson** [comment]
I added the update method. I'm not sure how useful it will be for the IK solves as they all store the limits as objects rather than pulling them from the SceneGraph::Ptr.

**Comment by Levi-Armstrong** [comment]
> I added the update method. I'm not sure how useful it will be for the IK solves as they all store the limits as objects rather than pulling them from the SceneGraph::Ptr.

What about adding a `setLimits` to the forward and inverse kinematics interface. Then let the manager loop over all kinematics objects and set there limits. It loop over and get the list of active joints from the kinematics objects and extract the data form the scene graph to build a new kinematics limits object.

**Comment by mpowelson** [comment]
With current changes, one breaking change is that ManipulatorManager is now in the namespace tesseract_environment instead of tesseract

**Comment by Levi-Armstrong** [comment]
I like the direction this going.

**Comment by mpowelson** [comment]
@Levi-Armstrong I think this is ready for a look. I wrote a unit test that I think shows that it is working. It is not checking the underlying KDL datastructures, but it should be changing them.

I am still recreating the KDL tree each time.  It should be nearly there for us to add functions to update each FK/IK solver individually as a performance improvement. However, I don't know if I will get to that right now.

**Comment by mpowelson** [comment]
Still todo. 

- Update tesseract_rosutils
- Add back in Tesseract::init(Environment)

**Comment by mpowelson** [comment]
@Levi-Armstrong Were you wanting me to merge this too?

**Review by Levi-Armstrong — APPROVED** [review]

**Pull request merged**
