### PR TITLE
Utilize parameter in TrajOpt planner

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@johnwason I am not sure why the python tests are failing for motion planning and the ones for c++ are passing due to the changes. Do you have any ideas?

**Comment by Levi-Armstrong** [comment]
Oh, @johnwason How can I run the python tests locally?

**Comment by johnwason** [comment]
You can run:

    python -m pytest

in the python test directory. You'll need to source the workspace and set TESSERACT_SUPPORT_DIR env variable before running. For Ubuntu Focal, run

    python3 -m pytest

**Comment by johnwason** [comment]
The freespace planner is using OMPL, so it may just be having random failures during that phase. Maybe try using a different workflow for that test.

**Comment by Levi-Armstrong** [comment]
Thanks, I also found an issues in the trajopt problem generator handling of fixed_states.

**Pull request merged**
