### PR TITLE
Remove jsoncpp and yaml-cpp from the tesseract_python_module.cmake

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@johnwason Do you mind reviewing?

**Comment by Levi-Armstrong** [comment]
This is to address issue #507

**Comment by johnwason** [comment]
tesseract_python modules do use json-cpp. https://github.com/ros-industrial-consortium/tesseract/blob/master/tesseract_python/tesseract_python/swig/json_typemaps.i

**Comment by Levi-Armstrong** [comment]
> tesseract_python modules do use json-cpp. https://github.com/ros-industrial-consortium/tesseract/blob/master/tesseract_python/tesseract_python/swig/json_typemaps.i

Ah, I added it back.

**Comment by Levi-Armstrong** [comment]
@johnwason This is ready now. I was getting build issues in another CI because some included header files which included symbols that were not being linked.

**Comment by Levi-Armstrong** [comment]
@johnwason Any objections with merging this?

**Pull request merged**
