### PR TITLE
Remove inheritance of std::vector from Composite Instruction

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
Having the CompositeInstruction inherit directly form std:vector was going to make python wrapper very difficult or even impossible leveraging SWIG. Same issues exists for the JointWaypoint and CartesianWaypoint. This remove the inheritance and adds all of the container methods required.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@johnwason Do you mind taking a look and let me know if you see any issues?

**Comment by Levi-Armstrong** [comment]
@johnwason I have change the Cartesian and Joint Waypoint where they do not inherit from Eigen types but still operate the same. Let me know if any additional changes need to be made to the these classes.

**Comment by Levi-Armstrong** [comment]
@mpowelson He made some possible breaking changes depending on how much you are using JointWaypoint and CartesianWaypoint as Eigen Types. I have added several methods so it plays nice with Eigen but you may need to further expose methods if you run into any issues.

**Comment by mpowelson** [comment]
Thanks for letting me know

**Comment by Levi-Armstrong** [comment]
Also added initializer_list support for the JointWaypoint.

**Comment by Levi-Armstrong** [comment]
@johnwason  We have been using this for a while without any issues so merging but if further changes are required to better support python please let me know and I will take of it.

**Pull request merged**
