### PR TITLE
Add support for user defined find tcp callbacks

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
This was added to support finding tcp when using ROS where it is only available via TF.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@colin-lewis-19 Ready to review.

**Comment by colin-lewis-19** [comment]
Understood. Pulling down for testing

**Comment by colin-lewis-19** [comment]
Seems to work as intended. Prevents planning if the TCP TF publisher is killed (if a camera driver were to crash, for instance), but those type of circumstances should probably be handled upstream anyways

**Comment by Levi-Armstrong** [comment]
@colin-lewis-19 It has been update to where findTCP will throw an exception if not found and updated motion planners to handle this exception to return failed plan with status ErrorInvalidInput.

**Pull request merged**
