### PR TITLE
Add cmake format

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
This formats cmake using [cmakelang](https://github.com/cheshirekow/cmake_format) format utility.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@haudren This PR formats the cmake using cmakelang. Do you have any input or recommendation for setting up the format file?

**Comment by haudren** [comment]
It looks pretty good as is, my main recommendations are quite simple, and you've followed them already:
- Keep everything to two spaces
- Break long lines in vertical layout beyond three items

I would however add a couple of other suggestions:
- Add the check to CI
- Make the keyword / command case consistent. I recommend keywords all uppercase and comand all lowercase e.g.
```
target_link_libraries(lib PRIVATE other_lib)
```

**Comment by Levi-Armstrong** [comment]
@haudren Thank you for the feedback. I have a few questions below.

> Break long lines in vertical layout beyond three items

You recommend setting both of these to three?
``` python
  # If an argument group contains more than this many sub-groups (parg or kwarg
  # groups) then force it to a vertical layout.
  max_subgroups_hwrap = 2

  # If a positional argument group contains more than this many arguments, then
  # force it to a vertical layout.
  max_pargs_hwrap = 5
```

> Add the check to CI

Do you have an example using this for a CI check?

**Comment by haudren** [comment]
What we have is actually:
```
  # If an argument group contains more than this many sub-groups (parg or kwarg
  # groups) then force it to a vertical layout.
  max_subgroups_hwrap = 2

  # If a positional argument group contains more than this many arguments, then
  # force it to a vertical layout.
  max_pargs_hwrap = 2
```

And something else I forgot, you might want to create custom commands for ROS things (and in general if you notice commands with arguments not being formatted properly):
```    "additional_commands": {
      "generate_dynamic_reconfigure_options": {
        "pargs": "*"
      },
      "add_rostest": {
        "pargs": "*",
        "flags": [],
        "kwargs": {
          "ARGS": "*",
          "DEPENDENCIES": "*"
        }
      },
      "catkin_install_python": {
        "pargs": "*",
        "flags": [],
        "kwargs": {
          "PROGRAMS": "*",
          "DESTINATION": "*"
        }
      },
      "catkin_package": {
        "pargs": "*",
        "flags": [],
        "kwargs": {
          "CATKIN_DEPENDS": "*",
          "INCLUDE_DIRS": "*",
          "LIBRARIES": "*"
        }
      },
      "generate_messages": {
        "pargs": "*",
        "flags": [],
        "kwargs": {
          "DEPENDENCIES": "*"
        }
      },
      "add_service_files": {
        "pargs": "*",
        "flags": [],
        "kwargs": {
          "FILES": "*"
        }
      },
      "add_message_files": {
        "pargs": "*",
        "flags": [],
        "kwargs": {
          "FILES": "*"
        }
      }
    },
```

For the CI check, I use something similar to what you currently have, but it doesn't run on Travis:
```
      find . \( -name CMakeLists.txt -o -name \*.cmake \) -exec cmake-format -i {} + 2>&1
      git diff -p 1>&2
```
And this step is set up to fail if anything is written to stderr.

**Pull request merged**
