### PR TITLE
Update Descartes and OMPL to leverage new Kinematics objects

### PR DESCRIPTION
**Pull request by mpowelson**
Then we can incrementally re enable features as we get them working and make sure they pass.

### CODE REVIEW

**Comment by mpowelson** [comment]
@Levi-Armstrong I didn't fix the issues in descartes since I knew you are working on it. I just disabled it as well as the process planners. Hopefully this will pass, then we can enable them as we submit PRs that fix the Clang issues.

**Comment by mpowelson** [comment]
@Levi-Armstrong This is passing now. I'm not sure how you want to combine this with #313 . You can probably cherrypick the commits other than clang-format without too much difficulty.

**Comment by Levi-Armstrong** [comment]
@mpowelson I believe that all changes have been applied to PR #313.

**Comment by mpowelson** [comment]
@Levi-Armstrong Hopefully this will still pass. I rearranged the clang-tidy commits and squashed them into one and left your 4 commits adding the positions and one with clang format.

**Comment by mpowelson** [comment]
Also, CI takes way longer on this build than on master. Did you add some crazy unit tests or something?

**Pull request merged**
